model = "gpt-5.6-sol"
model_reasoning_effort = "high"
[projects."/mnt/dev/PlannerBot"]
trust_level = "trusted"

[projects."/mnt/dev/dari"]
trust_level = "trusted"

[projects."/mnt/dev/Dari"]
trust_level = "trusted"

[projects."/home/dadyarri/.config/fish"]
trust_level = "trusted"

[projects."/mnt/dev/melodytrack-stuff/MelodyTrack"]
trust_level = "trusted"

[projects."/mnt/dev/MelodyTrack"]
trust_level = "trusted"

[projects."/home/dadyarri/Projects/MelodyTrack"]
trust_level = "trusted"

[projects."/home/dadyarri/Projects/MelodyTrack/MelodyTrack.Web"]
trust_level = "trusted"

[projects."/home/dadyarri/Projects/portfolio"]
trust_level = "trusted"

[projects."/home/dadyarri/Projects/dry"]
trust_level = "trusted"

[projects."/home/dadyarri/Projects/NexusSfx"]
trust_level = "trusted"

[projects."/home/dadyarri"]
trust_level = "trusted"

[projects."/home/dadyarri/Projects/dndsu_datasets"]
trust_level = "trusted"

[projects."/home/dadyarri/work/tries/planner_bot"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4

[notice.model_migrations]
"gpt-5.4" = "gpt-5.6-terra"

[hooks.state]

[hooks.state."/home/dadyarri/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:fc87dbee1cb8a9be4f78ba094c4fa8d5e2fd38cb800854e3717f9b6a52fe2a47"

[hooks.state."/home/dadyarri/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:ac371f260e4b23ba1d1b7a4ad68a44a323a8470b61f38471a47aceac1b7a5a7c"
[hooks.state."/home/dadyarri/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:1b1a100a9fa807d0949680e6fb28adfacc31a9b50560213a00d580803e6b1da7"
[hooks.state."/home/dadyarri/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:5fb1a1f81d3c4505ad5a35f2c6f0bd671f59de998ccb80551337d83ffee899a0"
[hooks.state."/home/dadyarri/.codex/hooks.json:permission_request:0:0"]
trusted_hash = "sha256:5e4fdce5f80486001f3e7497eb3b23feddc37967d2780fa9fbefa3ad3d7f5651"
[hooks.state."/home/dadyarri/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:ea0042547f66e83e9fe3a9d845fedba0cdc6ccfd8c220d432ba1a9820df9f63d"

[hooks.state."/home/dadyarri/.codex/hooks.json:pre_tool_use:1:0"]
trusted_hash = "sha256:bb70cb4e6b3b1c235d14fa6b5c5cc2687054e12a41d29da263b2c78629971a1c"
[features]
hooks = true
