EDITOR=micro
VISUAL=micro
PAGER=bat

DOTNET_ROOT=$HOME/.dotnet
PATH=$HOME/.local/bin:$DOTNET_ROOT:$DOTNET_ROOT/tools:$HOME/.cargo/bin:$HOME/.aspire/bin:$HOME/.atuin/bin:$PATH

SSL_CERT_DIR=$HOME/.aspnet/dev-certs/trust:/etc/ssl/certs
