-- Buffer-related options
vim.opt.autoindent = true
vim.opt.fileencoding = "utf-8"
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.tabstop = 4

-- Global options
vim.opt.background = "dark"
vim.opt.backup = false
vim.opt.clipboard = "unnamedplus"
vim.opt.cmdheight = 2
vim.opt.encoding = "utf-8"
vim.opt.ignorecase = true
vim.opt.mouse = "a"
vim.opt.showmode = false
vim.opt.smartcase = true
vim.opt.smarttab = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.writebackup = false
vim.opt.shortmess = "filnxtToOfc"
vim.opt.termguicolors = true
vim.opt.hidden = true

-- Window-related options
vim.opt.cursorline = true
vim.opt.number = true
vim.opt.relativenumber = true
