
[window]
dimensions = { columns = 108, lines = 30 }
padding = { x = 15, y = 15 }
opacity = 1
dynamic_title = false

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 15.00

[general]
import = [ "~/.config/alacritty/nord.toml" ]

[cursor]
style = { shape = "Beam", blinking = "On" }

[env]
SHELL = "fish"

[terminal]
shell = "zellij"

[[hints.enabled]]
command         = "xdg-open"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
mouse.mods      = "Control" # "Control|Shift" is my preference
binding         = { key = "O", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|go‐pher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
