[packages.cachyos]
repo = [
    "alacritty",
    "base-devel",
    "bat",
    "borg",
    "btop",
    "cachyos-rate-mirrors",
    "curl",
    "direnv",
    "docker",
    "docker-buildx",
    "docker-compose",
    "duf",
    "easytag",
    "eza",
    "fd",
    "ffmpeg",
    "fish",
    "flatpak",
    "fzf",
    "gifsicle",
    "git",
    "git-delta",
    "github-cli",
    "glances",
    "glow",
    "gum",
    "imagemagick",
    "iproute2",
    "jq",
    "meld",
    "micro",
    "obs-studio",
    "obsidian",
    "openssl",
    "ouch",
    "paru",
    "perl-image-exiftool",
    "python",
    "python-pipx",
    "qbittorrent",
    "ripgrep",
    "rsync",
    "sd",
    "shellcheck",
    "spectacle",
    "syncthing",
    "telegram-desktop",
    "television",
    "tokei",
    "trash-cli",
    "tree",
    "unrar",
    "unzip",
    "vlc",
    "wget",
    "wl-clipboard",
    "xclip",
    "xdg-user-dirs",
    "yt-dlp",
    "zellij",
    "zoxide",
]

aur = [
    "openlogi-bin",
    "localsend-bin",
    "syncthingtray-qt6",
    "ungoogled-chromium-bin",
    "try-rs-bin",
    "visual-studio-code-bin",
]

flatpak = [
    "it.mijorus.gearlever",
    "org.musicbrainz.Picard",
]
